---
- name: Ensure group "igroup" exists
  group:
    name: igroup
    state: present

- name: Add the user 'ipoque' with a specific password
  user:
    name: ipoque
    uid: 1001
    group: igroup
    password: "{{ password }}"
