version: '3.7'
services:
  openssh-server:
    build: .   
    image: ssh-server
    container_name: ssh-server
    volumes:
      - ./mount:/ansible 
    ports:
      - "2222:22"
    restart: unless-stopped
