---
# file: common.yml
- name: Apply common basic configuration to all servers
  hosts: managed
  gather_facts: false
  become: true
  pre_tasks:
  - name: Gathering facts
    setup:
  roles:
    - roles/ssh
